apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: serhiibuniak/apigateway:latest
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: apigateway
  ports:
  - name: apigateway
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
