apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blob-pvc
spec:
  selector:
    matchLabels:
      disk: blob-pvc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite:latest
          ports:
            - containerPort: 10000
            - containerPort: 10001
            - containerPort: 10002
          volumeMounts:
            - name: blob-pvc
              mountPath: /data
      volumes:
        - name: blob-pvc
          persistentVolumeClaim:
            claimName: blob-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: azurite-srv
spec:
  type: ClusterIP
  selector:
      app: azurite
  ports:
    - name: storage-azurite-blobs
      port: 10000
      targetPort: 10000
    - name: storage-azurite-queues
      port: 10001
      targetPort: 10001
    - name: storage-azurite-tables
      port: 10002
      targetPort: 10002
---
apiVersion: v1
kind: Service
metadata:
  name: azurite-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: azurite
  ports:
    - name: storage-azurite-blobs
      port: 10000
      targetPort: 10000
    - name: storage-azurite-queues
      port: 10001
      targetPort: 10001
    - name: storage-azurite-tables
      port: 10002
      targetPort: 10002