apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageservice
  template:
    metadata:
      labels:
        app: imageservice
    spec:
      containers:
        - name: imagemicroservice
          image: serhiibuniak/imagemicroservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: image-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: imageservice
  ports:
  - name: imageservice
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: image-np-srv
spec:
  type: NodePort
  selector:
    app: imageservice
  ports:
    - name: imageservice
      protocol: TCP
      port: 80
      targetPort: 80